### ISSUE TITLE
Php artisan settings:publish fails with error

### ISSUE THREAD

**Issue by progonitelj** [DarkGhostHunter/Laraconfig#11]
Hi, 

it's me again. Sorry to bother you but when I run a command: php artisan settings:publish it fails with an error.

Error: ** copy(Laravel\settings/users.php): Failed to open stream: No such file or directory
**

I created the directory and file myself so when I run command again it created a symbolic link in laraconfig/stubs/users.php.

Thanks for everything this library looks awesome!

**Comment by progonitelj** [comment]
Also when I run a command **php artisan settings:migrate** I get the following error:

  Illuminate\Contracts\Container\BindingResolutionException 

  Target [Symfony\Component\Console\Output\OutputInterface] is not instantiable while building [DarkGhostHunter\Laraconfig\Migrator\Pipes\FlushCache, Illum
inate\Console\OutputStyle].


Thanks again!

**Comment by DarkGhostHunter** [comment]
[Fixed on 1.3.3](https://github.com/DarkGhostHunter/Laraconfig/releases/tag/v1.3.3).
