### ISSUE TITLE
Still getting the error

### ISSUE THREAD

**Issue by progonitelj** [DarkGhostHunter/Laraconfig#15]
When I run **php artisan settings:migrate** I still get the following error:

Illuminate\Contracts\Container\BindingResolutionException

Target [Symfony\Component\Console\Output\OutputInterface] is not instantiable while building [DarkGhostHunter\Laraconfig\Migrator\Pipes\FlushCache, Illum
inate\Console\OutputStyle].

I also tried to reinstall the package.

I get the same error like before when I try to publish the package with the command **php artisan vendor:publish --provider="DarkGhostHunter\Laraconfig\LaraconfigServiceProvider" --tag="migrations"**

ERROR: 
Unable to locate publishable resources.
Publishing complete.

Also when I run a command **php artisan settings:publish**

I get the error:
                                                              
  There are no commands defined in the "settings" namespace.

**Comment by DarkGhostHunter** [comment]
Definitely something is real bad in your end.

Check you're running v1.3.4, and dump the autoload just to be sure.

**Comment by progonitelj** [comment]
Everything works now!

Thank you for your quick responses on my issues!
