### ISSUE TITLE
Column not found: 1054 Unknown column '1' in 'field list'

### ISSUE THREAD

**Issue by mprince2k18** [DarkGhostHunter/Laraconfig#16]
![image](https://user-images.githubusercontent.com/43857625/126957256-5f80702f-c17c-4bac-b5bc-19153579d777.png)

after settings:migrate command facing this error in the CLI.

**Comment by DarkGhostHunter** [comment]
It seems that the SQL to migrate needs to use raw statements.

I pushed an update to the master branch. Try again, it should be fixed now that it enforces raw statements which will make the difference between a hard-coded value and a column name in the field list.

**Comment by lucasjose501** [comment]
Had the same problem, the master branch fixed it

**Comment by DarkGhostHunter** [comment]
I'll wait for @mprince2k18 and, if it's a success, push it to `stable`.

**Comment by mprince2k18** [comment]
Hi, Thanks It's working now. <3

**Comment by DarkGhostHunter** [comment]
Fixed on v1.3.5
