### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by progonitelj** [DarkGhostHunter/Laraconfig#8]
Hi, 

when I run command - _php artisan vendor:publish --provider="DarkGhostHunter\Laraconfig\LaraconfigServiceProvider" --tag="migrations"_ 

I get the error:
**Unable to locate publishable resources.
Publishing complete.**

Before the command above i have entered: composer require darkghosthunter/laraconfig

Am i doing something wrong?

**Comment by DarkGhostHunter** [comment]
Totally forgot to remove the [`!class_exists($class)`](https://github.com/DarkGhostHunter/Laraconfig/commit/acd0140aad1c198985c110be0e0f02ede4ccc710#diff-4bb3ddd098e119e61c90804b79f290e0bf9f1a004e1a50a24f1333756a84ea19R65-R69) bit. 

I added that to not register migrations if the class was already loaded to avoid this error when loading the migrations:

    PHP Fatal error:  Cannot declare class [CreateSomethingTable], because the name is already in use

This, instead, treats them as any publishable asset. I just forgot to remove the `if` from the old code.

[It's fixed on v1.3.1](https://github.com/DarkGhostHunter/Laraconfig/releases/tag/v1.3.1)

**Comment by progonitelj** [comment]
Thank you very much for a quick fix. 
I was going to implement user settings for my Vue app when I saw this awesome library on Reddit!
Keep up the good work!

**Comment by progonitelj** [comment]
I tried to update to v1.3.1 and I still get the error:
Command: _php artisan vendor:publish --provider="DarkGhostHunter\Laraconfig\LaraconfigServiceProvider" --tag="migrations"_

Error: **Unable to locate publishable resources.
Publishing complete.**

Maybe I'm doing something wrong?

**Comment by DarkGhostHunter** [comment]
No, you did nothing wrong. It was [this line](https://github.com/DarkGhostHunter/Laraconfig/blob/4a368dcf1e6b03335f8068ccd0146db8573b5869/composer.json#L40).

Should be fixed now in 1.3.2.
